version: '2'
services:
  mysql:
    image: nginx
    restart: always
    volumes:
      - ./files/ssl:/etc/nginx/ssl
      - ./files/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./files/certs/nginx.pem:/etc/nginx/certs/nginx.pem
    ports:
      - 80:8081/tcp
      - 8443:443/tcp
