version: '2'
services:
  mysql:
    image: nginx
    restart: always
    volumes:
      - ./files/conf.d/hosts:/etc/hosts
      - ./files/ssl:/etc/nginx/ssl
      - ./files/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./files/certs/nginx.pem:/etc/nginx/certs/nginx.pem
    ports:
      - 8088:80/tcp
      - 443:443/tcp
